server:
  port: 8083

spring:
  application:
    name: email-sender

  kafka:
    bootstrap-servers: ${AIVEN_HOST}

    properties:
      security.protocol: SSL
      ssl.truststore.location: file:/tmp/client.truststore.jks
      ssl.truststore.password: changeit
      ssl.truststore.type: PKCS12
      ssl.keystore.location: file:/tmp/client.keystore.jks
      ssl.keystore.password: changeit
      ssl.keystore.type: PKCS12
      ssl.key.password: changeit

    consumer:
      group-id: email-group
      auto-offset-reset: earliest
      enable-auto-commit: false

      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer

        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.roridea.email_sender.dto.EmailEventDto

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    listener:
      ack-mode: record

sendgrid:
  api-key: ${APIKEY}
  from-email: ${MAILFROM}

KAFKA_TRUSTSTORE_BASE64: ${KAFKA_TRUSTSTORE_BASE64}
KAFKA_KEYSTORE_BASE64: ${KAFKA_KEYSTORE_BASE64}